[workspace]
members = [
  "xrd",
  "xrd/sys",
  "gxr",
  "gxr/sys",
  "gulkan",
  "gulkan/sys",
  "app",
]

[patch.crates-io]
glium = { path = "./glium" }

[profile.release]
panic = "abort"
lto = "thin"

[profile.dev]
panic = "abort"
